# Generated by Django 5.0.7 on 2024-07-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='comedy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='concert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.BooleanField(default=False),
        ),
    ]
